### ISSUE TITLE
TrackData is undefined

### ISSUE THREAD

**Issue by Steffeng5** [openbikesensor/obsAPI#24]
Since a198cb620bab7915eb200d98cb3b0c1ef79ee2cd no TrackData is received anymore

The GET Request to /TrackData is unsuccessful because req.track.trackData is undefined

**Comment by opatut** [comment]
I cannot reproduce that.  Do you have a stack trace? Did you run migrations?

**Comment by Steffeng5** [comment]
This was because of your missing commits. you already fixed that :)
